UPSTREAM: Revert "pw_trace_tokenized: Use InlineVarLenEntryQueue for trace buffer"
This reverts commit 8d47bd657be092b08a50ee2835a4ad4af9cbec42.

Reason for revert: Fetching trace data via pw_transfer fails with error:
pw_transfer.client.Error: Transfer 1 failed with status Status.INTERNAL

Original change's description:
> pw_trace_tokenized: Use InlineVarLenEntryQueue for trace buffer
>
> Bug: 437155622
> Change-Id: Ic32231e879232076c8a52325ccf7f316422386c5
> Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/316736
> Reviewed-by: Wyatt Hepler <hepler@google.com>
> Presubmit-Verified: CQ Bot Account <pigweed-scoped@luci-project-accounts.iam.gserviceaccount.com>
> Tests-Not-Needed: Aaron Green <aarongreen@google.com>
> Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
> Commit-Queue: Aaron Green <aarongreen@google.com>

# Not skipping CQ checks because original CL landed > 1 day ago.

(cherry picked from commit ea90565a22d14385b600eae9d962fbe2de92f225)

Original-Bug: 437155622
Original-Change-Id: Id0f3dea0677ba9429070c74f09e9e0a81a1fdf6c
Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/338592
Original-Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Original-Reviewed-by: Jonathon Reinhart <jrreinhart@google.com>
Original-Reviewed-by: Aaron Green <aarongreen@google.com>
Original-Commit-Queue: Austin Foxley <afoxley@google.com>
Original-Pigweed-Auto-Submit: Austin Foxley <afoxley@google.com>
Original-Presubmit-Verified: CQ Bot Account <pigweed-scoped@luci-project-accounts.iam.gserviceaccount.com>
GitOrigin-RevId: ea90565a22d14385b600eae9d962fbe2de92f225
Cr-Build-Id: 8699832925516592321
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8699832925516592321
Copybot-Job-Name: pigweed-main-copybot-downstream
Change-Id: If37644e35857ec039020b3b7f7865e64bd8b40b7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/pigweed/pigweed/+/7087756
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>